### ISSUE TITLE
Loading Steam API failed

### ISSUE THREAD

**Issue by SwissKerim** [mbround18/palworld-docker#4]
I have STEAM API Errors, after i started the container initially with default docker-compose settings. 
"Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory"
after downloading and installing:
"[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded."

I use Portainer to deploy the compose.

Connection to server also not working

Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file

**Comment by mbround18** [comment]
This is normal, your server is running successfully. please check you firewall configurations and try restarting the container.
