### ISSUE TITLE
Game Parameters

### ISSUE THREAD

**Issue by stayupthetree** [mbround18/palworld-docker#6]
I want to launch the dedicated server with the follow paramenters "-useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS"

Is there a way to apply this? I see in this other Docker Container for Palworld its an Environmental Variable, not sure if that would apply here however.

If not no worries. I appreciate your work here! Thank you!

**Comment by mbround18** [comment]
@stayupthetree 
```
MULTITHREADING=true
```
https://github.com/mbround18/palworld-docker/blob/main/scripts/utils.sh#L51-L53

ill add this to the readme :)

**Comment by stayupthetree** [comment]
Thank you so much!
