### ISSUE TITLE
4 Environment Variables Not Working

### ISSUE THREAD

**Issue by stayupthetree** [mbround18/palworld-docker#7]
I noticed that I got raided despite setting ENABLE_INVADER_ENEMY to false, so I looked at the ini and it was still set to true. I dug around and noticed that while the readme has ENABLE_INVADER_ENEMY in the config.py and other files it is B_ENABLE_INVADER_ENEMY that everything is looking for. Same for the following

    "b_enable_player_to_player_damage": "False",
    "b_enable_friendly_fire": "False",
    "b_enable_invader_enemy": "True",
    "b_active_unko": "False",

Sorry if I am being a nuisance with all these issues

**Comment by mbround18** [comment]
No no not at all no worries on the issues, those should be: 

```
B_ENABLE_PLAYER_TO_PLAYER_DAMAGE
B_ENABLE_FRIENDLY_FIRE
B_ENABLE_INVADER_ENEMY
B_ACTIVE_UNKO
```

![Screenshot 2024-01-31 005828](https://github.com/mbround18/palworld-docker/assets/12646562/15884c64-e1a3-4b78-b00e-ea46468f3b95)

I can update in the docs to reflect the `B_` prefixer

**Comment by mbround18** [comment]
Updated the docs :) [5a50724](https://github.com/mbround18/palworld-docker/commit/5a507241f4f84ddb5242abb7a9a07b05d7245cde)
